### ISSUE TITLE
Encounter failure with uniVocity parser while running the comparison

### ISSUE THREAD

**Issue by xuchuanyin** [uniVocity/csv-parsers-comparison#21]
I ran the comparison test in windows MING32 env and encounter this faiure:

```
...
Loop 6 - executing CSVeed... Parser CSVeed threw exception: Illegal state transition: Parsing symbo
l QUOTE_SYMBOL [34] in state INSIDE_FIELD
Loop 6 - executing Bean IO Parser... Parser Bean IO Parser threw exception: Quotation character '"'
 must be quoted at line 19970
Loop 6 - executing Apache Commons CSV... took 4584 ms to read 3173959 rows.
Loop 6 - executing Esperio CSV parser... Parser Esperio CSV parser threw exception: Encountered une
xpected character "
Loop 6 - executing Gen-Java CSV... took 3011 ms to read 3173959 rows.
Loop 6 - executing Java CSV Parser... took 3039 ms to read 3173959 rows.
Loop 6 - executing JCSV Parser... took 2934 ms to read 3173959 rows.
Loop 6 - executing OpenCSV... took 3257 ms to read 3173959 rows.
Loop 6 - executing Simple CSV parser... took 2868 ms to read 3173959 rows.
Loop 6 - executing SuperCSV... took 3147 ms to read 3173958 rows.
Loop 6 - executing uniVocity CSV parser... Parser uniVocity CSV parser threw exception: java.lang.A
rrayIndexOutOfBoundsException - 512
Hint: Number of columns processed may have exceeded limit of 512 columns. Use settings.setMaxColumn
s(int) to define the maximum number of columns your input can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the i
nput format you are trying to parse
Parser Configuration: CsvParserSettings:
        Auto configuration enabled=true
        Autodetect column delimiter=false
        Autodetect quotes=false
        Column reordering enabled=false
        Empty value=null
        Escape unquoted values=false
        Header extraction enabled=null
        Headers=null
        Ignore leading whitespaces=false
        Ignore trailing whitespaces=false
        Input buffer size=1048576
        Input reading on separate thread=true
        Keep escape sequences=false
        Keep quotes=false
        Length of content displayed on error=-1
        Line separator detection enabled=false
        Maximum number of characters per column=4096
        Maximum number of columns=512
        Normalize escaped line separators=true
        Null value=null
        Number of records to read=all
        Processor=com.univocity.articles.csvcomparison.parser.UnivocityParser$1
        Restricting data in exceptions=false
        RowProcessor error handler=null
        Selected fields=none
        Skip bits as whitespace=true
        Skip empty lines=false
        Unescaped quote handling=nullFormat configuration:
        CsvFormat:
                Comment character=#
                Field delimiter=,
                Line separator (normalized)=\n
                Line separator sequence=\r\n
                Quote character="
                Quote escape character="
                Quote escape escape character=null
Internal state when error was thrown: line=0, column=513, record=0, charIndex=3859
Loop 6 - executing Way IO Parser... took 4474 ms to read 3173959 rows.
Loop 6 - executing Oster Miller CSV parser... took 3229 ms to read 3173959 rows.
Loop 6 - executing Jackson CSV parser... took 2344 ms to read 3173959 rows.
Loop 6 - executing SimpleFlatMapper CSV parser... took 1882 ms to read 3173959 rows.
Loop 6 - executing Product Collections parser... took 3178 ms to read 3173959 rows.
Loop 6 - executing Diergo Easy CSV Streamable... took 2728 ms to read 3173959 rows.

=========
 AVERAGES
=========

| uniVocity CSV parser   | -1 ms Could not execute
| SimpleFlatMapper CSV parser    | 1910 ms       | Best time!    | 1790 ms       | 1996 ms |
| Jackson CSV parser     | 2315 ms       | 21%           | 2206 ms       | 2455 ms |
| Diergo Easy CSV Streamable     | 2718 ms       | 42%           | 2558 ms       | 2785 ms |
| Simple CSV parser      | 2733 ms       | 43%           | 2592 ms       | 2871 ms |
| JCSV Parser    | 2793 ms       | 46%           | 2629 ms       | 2934 ms |
| Gen-Java CSV   | 2969 ms       | 55%           | 2810 ms       | 3051 ms |
| Java CSV Parser        | 3012 ms       | 57%           | 2925 ms       | 3167 ms |
| SuperCSV       | 3097 ms       | 62%           | 2931 ms       | 3293 ms |
| Product Collections parser     | 3117 ms       | 63%           | 2927 ms       | 3208 ms |
| OpenCSV        | 3173 ms       | 66%           | 3062 ms       | 3257 ms |
| Oster Miller CSV parser        | 3329 ms       | 74%           | 3229 ms       | 3421 ms |
| Apache Commons CSV     | 4427 ms       | 131%          | 4139 ms       | 4638 ms |
| Way IO Parser          | 4537 ms       | 137%          | 4359 ms       | 4756 ms |
Exception in thread "main" com.univocity.parsers.common.TextParsingException: java.lang.ArrayIndexO
utOfBoundsException - 512
Hint: Number of columns processed may have exceeded limit of 512 columns. Use settings.setMaxColumn
s(int) to define the maximum number of columns your input can have
Ensure your configuration is correct, with delimiters, quotes and escape sequences that match the i
nput format you are trying to parse
Parser Configuration: CsvParserSettings:
        Auto configuration enabled=true
        Autodetect column delimiter=false
        Autodetect quotes=false
        Column reordering enabled=true
        Empty value=null
        Escape unquoted values=false
        Header extraction enabled=null
        Headers=null
        Ignore leading whitespaces=true
        Ignore trailing whitespaces=true
        Input buffer size=1048576
        Input reading on separate thread=true
        Keep escape sequences=false
        Keep quotes=false
        Length of content displayed on error=-1
        Line separator detection enabled=false
        Maximum number of characters per column=4096
        Maximum number of columns=512
        Normalize escaped line separators=true
        Null value=null
        Number of records to read=all
        Processor=none
        Restricting data in exceptions=false
        RowProcessor error handler=null
        Selected fields=none
        Skip bits as whitespace=true
        Skip empty lines=true
        Unescaped quote handling=nullFormat configuration:
        CsvFormat:
                Comment character=#
                Field delimiter=,
                Line separator (normalized)=\n
                Line separator sequence=\r\n
                Quote character="
                Quote escape character="
                Quote escape escape character=null
Internal state when error was thrown: line=0, column=513, record=0, charIndex=3859
        at com.univocity.parsers.common.AbstractParser.handleException(AbstractParser.java:364)
        at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:508)
        at com.univocity.articles.csvcomparison.HugeFileGenerator.generateHugeFile(HugeFileGenerato
r.java:44)
        at com.univocity.articles.csvcomparison.PerformanceComparison.main(PerformanceComparison.ja
va:213)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 512
        at com.univocity.parsers.common.ParserOutput.valueParsed(ParserOutput.java:318)
        at com.univocity.parsers.csv.CsvParser.parseRecord(CsvParser.java:135)
        at com.univocity.parsers.common.AbstractParser.parseNext(AbstractParser.java:473)
        ... 2 more
```

**Comment by jbax** [comment]
Ah the line ending is not set to `\n`: 

See: `Line separator sequence=\r\n` - this is the default used in Windows so that's why the parser doesn't find the end of the record.

**Comment by jbax** [comment]
Adjusted. Not sure about the other parsers. Will have to revisit them later.
Thanks for letting me know.

**Comment by xuchuanyin** [comment]
hi @jbax thanks for your quick response!
After applying your commit, the problem is still there, so I continue to fix it following your instruction. Please check PR #22

**Comment by xuchuanyin** [comment]
The final result looks like below:

![image](https://user-images.githubusercontent.com/10445758/47772892-1cb4b980-dd23-11e8-93c9-6c54bd38b338.png)

UniVocity parser is awesome
